"""
MoleculeChecker — SynAgent Module 1
====================================
Validates molecules generated by SmileyLlama before they enter the docking
pipeline or DPO feedback loop. Runs 8 sequential checks ordered from cheapest
to most expensive; a molecule is killed at the first failed check.

Context: CACHE Challenge 8, GID4 ligand discovery.
The dominant failure mode in Joe's data is sulfonamide overload (82% of kills)
caused by a reward function bug that incentivizes piling on sulfonamide groups.

Usage:
    checker = MoleculeChecker()
    result  = checker.check("CCO")           # single SMILES
    results = checker.check_batch(smiles_list)

    # Load directly from the SDF files in top_poses.tar
    results = checker.check_from_tar("top_poses.tar-3/top_poses.tar-3")
"""

import os
import sys
import tarfile
import io

from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors, FilterCatalog
from rdkit.Chem.FilterCatalog import FilterCatalogParams
from rdkit.Chem import RDConfig

# SA Score lives in RDKit's contrib folder, not the main package.
sys.path.append(os.path.join(RDConfig.RDContribDir, "SA_Score"))
import sascorer


# ─────────────────────────────────────────────────────────────────────────────
# Reactive / unstable substructure patterns (Check 3)
# Each tuple is (human-readable name, SMARTS string, reason it's bad).
# ─────────────────────────────────────────────────────────────────────────────
REACTIVE_PATTERNS = [
    ("Peroxide",     "[OX2][OX2]",              "Explosive O-O bond"),
    ("Azide chain",  "[N-]=[N+]=[N]",            "Explosive, shock-sensitive"),
    ("Acyl halide",  "[CX3](=O)[F,Cl,Br,I]",    "Hydrolyzes instantly in water"),
    ("Rhodanine",    "O=C1CSC(=S)N1",            "Known PAINS scaffold"),
    ("Catechol",     "c1cc(O)c(O)cc1",           "Metal chelator, assay interference"),
    ("Hydrazine",    "[NH][NH]",                  "Toxic metabolite risk"),
]

# Salt-bridge-capable groups (Check 8 — advisory only, does not kill)
# GID4's GLU237 forms a salt bridge with basic amines; we flag their presence.
SALT_BRIDGE_PATTERNS = [
    ("Primary amine",   "[NH2;!$(NC=O);!$(NS=O)]"),
    ("Secondary amine", "[NH1;!$(NC=O);!$(NS=O);!$(Nc)]"),
    ("Guanidinium",     "[NH]C(=[NH])[NH2]"),
    ("Piperidine",      "C1CCNCC1"),
    ("Piperazine",      "C1CNCCN1"),
]

# Sulfonamide SMARTS (Check 7).
# Joe's reward function bug causes SmileyLlama to overload molecules with these.
SULFONAMIDE_SMARTS = "[#7]S(=O)(=O)"

# ─────────────────────────────────────────────────────────────────────────────
# Drug-likeness thresholds (Check 5, Lipinski + Veber rules adapted for CACHE 8)
# ─────────────────────────────────────────────────────────────────────────────
DRUG_LIKENESS_RULES = {
    "MW":       (200,  550),   # molecular weight — upper limit tightened vs. Ro5's 500
    "LogP":     (None,   5.0), # lipophilicity — only upper bound matters here
    "HBD":      (None,   5),   # hydrogen bond donors
    "HBA":      (None,  10),   # hydrogen bond acceptors
    "RotBonds": (None,  10),   # rotatable bonds (flexibility)
    "TPSA":     (20,   140),   # topological polar surface area
    "Fsp3":     (0.2, None),   # fraction sp3 carbons — want some 3D character
}


class CheckResult:
    """Holds the outcome of a single molecule check."""

    def __init__(self, smiles: str):
        self.smiles        = smiles
        self.passed        = False
        self.kill_reason   = None   # set if the molecule is rejected
        self.warnings      = []     # non-fatal observations (e.g. advisory checks)
        self.properties    = {}     # computed descriptors logged for reporting
        # metadata copied from the SDF if loaded from a file
        self.mol_index     = None
        self.iteration     = None
        self.protein       = None
        self.total_score   = None
        self.gid4_dock     = None
        self.iminer        = None

    def __repr__(self):
        status = "PASS" if self.passed else f"FAIL ({self.kill_reason})"
        return f"<CheckResult {status} | {self.smiles[:40]}>"


class MoleculeChecker:
    """
    Runs 8 sequential validation checks on a SMILES string.

    Checks are ordered cheapest → most expensive so a bad molecule is killed
    as early as possible with minimal compute.

        1. Structural validity    ~0.01 ms
        2. Charge check           ~0.01 ms
        3. Stability check        ~0.05 ms
        4. PAINS filter           ~0.10 ms
        5. Drug-likeness          ~0.05 ms
        6. SA score               ~1.00 ms
        7. Sulfonamide count      ~0.05 ms
        8. Salt bridge (advisory) ~0.05 ms   ← does NOT kill

    Total: ~1.3 ms / molecule.
    """

    def __init__(self, sulfonamide_limit: int = 3, sa_score_limit: float = 6.0):
        """
        Parameters
        ----------
        sulfonamide_limit : int
            Molecules with >= this many sulfonamide groups are killed.
            Default 3 matches Joe's spec.
        sa_score_limit : float
            SA score cutoff (1 = trivially easy to synthesize, 10 = impossible).
            Default 6.0 removes only the most synthetically inaccessible molecules.
        """
        self.sulfonamide_limit = sulfonamide_limit
        self.sa_score_limit    = sa_score_limit

        # Pre-compile reactive SMARTS patterns once at init time so we're not
        # recompiling them on every molecule (would be slow for large batches).
        self._reactive = [
            (name, Chem.MolFromSmarts(smarts), reason)
            for name, smarts, reason in REACTIVE_PATTERNS
        ]
        self._salt_bridge = [
            (name, Chem.MolFromSmarts(smarts))
            for name, smarts in SALT_BRIDGE_PATTERNS
        ]
        self._sulfonamide_pat = Chem.MolFromSmarts(SULFONAMIDE_SMARTS)

        # Build the RDKit PAINS catalog once — it's an in-memory lookup table.
        params = FilterCatalogParams()
        params.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS)
        self._pains_catalog = FilterCatalog.FilterCatalog(params)

    # ─────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────

    def check(self, smiles: str, metadata: dict = None) -> CheckResult:
        """
        Run all 8 checks on a single SMILES string.

        Parameters
        ----------
        smiles   : SMILES string to validate
        metadata : optional dict of SDF fields (mol_index, iteration, etc.)

        Returns
        -------
        CheckResult with .passed, .kill_reason, .warnings, .properties
        """
        result = CheckResult(smiles)

        # Copy SDF metadata onto the result object for easy reporting later.
        if metadata:
            for key in ("mol_index", "iteration", "protein",
                        "total_score", "gid4_dock", "iminer"):
                setattr(result, key, metadata.get(key))

        # Run checks in order; stop at the first failure.
        mol = self._check_structure(smiles, result)
        if mol is None:
            return result  # killed by Check 1

        if not self._check_charge(mol, result):
            return result  # killed by Check 2

        if not self._check_stability(mol, result):
            return result  # killed by Check 3

        if not self._check_pains(mol, result):
            return result  # killed by Check 4

        if not self._check_drug_likeness(mol, result):
            return result  # killed by Check 5

        if not self._check_sa_score(mol, result):
            return result  # killed by Check 6

        if not self._check_sulfonamides(mol, result):
            return result  # killed by Check 7

        # Check 8 is advisory — never kills, just adds to warnings.
        self._check_salt_bridge(mol, result)

        result.passed = True
        return result

    def check_batch(self, smiles_list: list, metadata_list: list = None) -> list:
        """
        Run checks on a list of SMILES strings.

        Parameters
        ----------
        smiles_list   : list of SMILES strings
        metadata_list : optional list of metadata dicts aligned with smiles_list

        Returns
        -------
        List of CheckResult objects, one per input SMILES.
        """
        if metadata_list is None:
            metadata_list = [None] * len(smiles_list)

        results = []
        for smiles, meta in zip(smiles_list, metadata_list):
            results.append(self.check(smiles, meta))
        return results

    def check_from_tar(self, tar_path: str) -> list:
        """
        Load SMILES directly from all .sdf files inside a tar archive and run
        the full check pipeline on each molecule.

        The SDF files in top_poses.tar-3 each contain one molecule with fields:
            <smiles>, <iteration>, <mol_index>, <total_score>,
            <gid4_dock>, <iminer>, <logs>, <protein>

        Parameters
        ----------
        tar_path : path to the .tar / .tar.gz file

        Returns
        -------
        List of CheckResult objects, one per SDF file.
        """
        results = []
        with tarfile.open(tar_path, "r:*") as tar:
            sdf_members = [m for m in tar.getmembers() if m.name.endswith(".sdf")]
            for member in sdf_members:
                f = tar.extractfile(member)
                if f is None:
                    continue
                content = f.read().decode("utf-8", errors="replace")
                smiles, metadata = self._parse_sdf(content)
                if smiles:
                    results.append(self.check(smiles, metadata))
        return results

    def summary(self, results: list) -> dict:
        """
        Compute aggregate statistics from a list of CheckResult objects.

        Returns a dict with counts and percentages, mirroring the table in the
        design doc Section 5.1.
        """
        total   = len(results)
        passed  = sum(1 for r in results if r.passed)
        failed  = total - passed

        # Tally the kill reason for every failed molecule.
        # Normalise MW kill reasons to a single bucket so the summary table
        # doesn't have one row per unique MW value.
        kill_counts = {}
        for r in results:
            if not r.passed and r.kill_reason:
                reason = r.kill_reason
                if reason.startswith("Drug-likeness: MW"):
                    prop = reason.split(":")[1].split("=")[0].strip()   # "MW"
                    op   = ">" if ">" in reason else "<"
                    lim  = reason.split(op)[1].strip()
                    reason = f"Drug-likeness: {prop} {op} {lim}"
                kill_counts[reason] = kill_counts.get(reason, 0) + 1

        # Count how many molecules have a salt bridge group (advisory field).
        salt_bridge_count = sum(
            1 for r in results
            if any("salt bridge" in w.lower() for w in r.warnings)
        )

        return {
            "total":             total,
            "passed":            passed,
            "passed_pct":        round(100 * passed / total, 1) if total else 0,
            "failed":            failed,
            "failed_pct":        round(100 * failed / total, 1) if total else 0,
            "kill_breakdown":    kill_counts,
            "salt_bridge_count": salt_bridge_count,
            "salt_bridge_pct":   round(100 * salt_bridge_count / total, 1) if total else 0,
        }

    def print_summary(self, results: list):
        """Print a human-readable summary table to stdout."""
        s = self.summary(results)
        print("\n" + "=" * 55)
        print("  MoleculeChecker Results")
        print("=" * 55)
        print(f"  Total molecules analyzed : {s['total']}")
        print(f"  PASSED all checks        : {s['passed']} ({s['passed_pct']}%)")
        print(f"  FAILED                   : {s['failed']} ({s['failed_pct']}%)")
        print(f"  Has salt bridge group    : {s['salt_bridge_count']} ({s['salt_bridge_pct']}%)")
        print("\n  Kill reason breakdown:")
        for reason, count in sorted(s["kill_breakdown"].items(),
                                    key=lambda x: -x[1]):
            pct = round(100 * count / s["total"], 1)
            print(f"    {reason:<35} {count:>4}  ({pct}%)")
        print("=" * 55 + "\n")

    # ─────────────────────────────────────────────────────────────────
    # Check 1 — Structural Validity
    # ─────────────────────────────────────────────────────────────────

    def _check_structure(self, smiles: str, result: CheckResult):
        """
        Attempt to parse the SMILES and sanitize the resulting molecule.

        What it catches:
          - Malformed SMILES (unmatched parentheses, unknown atom symbols, etc.)
          - Valence errors (e.g. carbon with 5 bonds)
          - Disconnected fragments (salts, solvent molecules left in)
          - Unreasonably small or large molecules

        Returns the RDKit Mol object on success, or None if the molecule is killed.
        The result object is mutated in-place with kill_reason on failure.
        """
        # MolFromSmiles returns None for unparseable strings; it already calls
        # SanitizeMol internally, so we get valence checking for free.
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            result.kill_reason = "Invalid SMILES (unparseable or bad valence)"
            return None

        # Disconnected fragments — a dot in SMILES means multiple components.
        # More than 1 fragment usually means a salt that hasn't been stripped.
        frags = Chem.GetMolFrags(mol)
        if len(frags) > 1:
            result.kill_reason = f"Disconnected fragments ({len(frags)} components)"
            return None

        # Sanity-check atom count.  < 5 is too small to be a real drug candidate;
        # > 100 heavy atoms is almost certainly a polymer or aggregator.
        heavy_atoms = mol.GetNumHeavyAtoms()
        if heavy_atoms < 5:
            result.kill_reason = f"Too small ({heavy_atoms} heavy atoms)"
            return None
        if heavy_atoms > 100:
            result.kill_reason = f"Too large ({heavy_atoms} heavy atoms)"
            return None

        result.properties["heavy_atoms"] = heavy_atoms
        return mol

    # ─────────────────────────────────────────────────────────────────
    # Check 2 — Charge Check
    # ─────────────────────────────────────────────────────────────────

    def _check_charge(self, mol, result: CheckResult) -> bool:
        """
        Reject molecules with unrealistic formal charges.

        SmileyLlama in earlier RL iterations generated triply-charged molecules
        to maximize predicted salt-bridge interaction scores — pure reward hacking.

        Rules enforced:
          - Total formal charge must be in [-2, +2]
          - No more than 3 individually charged atoms
          - Charge density < 0.15 per heavy atom (catches small but over-charged mols)

        Returns True if the molecule passes, False if it is killed.
        """
        total_charge = Chem.GetFormalCharge(mol)
        result.properties["formal_charge"] = total_charge

        if abs(total_charge) > 2:
            result.kill_reason = f"Excessive total charge ({total_charge:+d})"
            return False

        # Count the number of atoms that carry any formal charge.
        charged_atoms = sum(
            1 for atom in mol.GetAtoms() if atom.GetFormalCharge() != 0
        )
        result.properties["charged_atoms"] = charged_atoms

        if charged_atoms > 3:
            result.kill_reason = f"Too many charged atoms ({charged_atoms})"
            return False

        # Charge density check — avoids zwitterions with 3 identical charges on
        # a tiny scaffold.
        heavy_atoms = mol.GetNumHeavyAtoms()
        charge_density = charged_atoms / heavy_atoms
        if charge_density > 0.15:
            result.kill_reason = (
                f"Charge density too high "
                f"({charged_atoms} charges / {heavy_atoms} atoms = {charge_density:.2f})"
            )
            return False

        return True

    # ─────────────────────────────────────────────────────────────────
    # Check 3 — Stability / Reactive Groups
    # ─────────────────────────────────────────────────────────────────

    def _check_stability(self, mol, result: CheckResult) -> bool:
        """
        Reject molecules containing chemically unstable or dangerous substructures.

        Each pattern in REACTIVE_PATTERNS is checked via substructure matching.
        Even one hit kills the molecule — these functional groups make a compound
        unsuitable as a drug candidate regardless of its docking score.

        Returns True if no reactive groups are found, False otherwise.
        """
        for name, pattern, reason in self._reactive:
            if mol.HasSubstructMatch(pattern):
                result.kill_reason = f"Reactive group: {name} — {reason}"
                return False
        return True

    # ─────────────────────────────────────────────────────────────────
    # Check 4 — PAINS Filter
    # ─────────────────────────────────────────────────────────────────

    def _check_pains(self, mol, result: CheckResult) -> bool:
        """
        Reject Pan-Assay INterference compoundS (PAINS).

        PAINS are molecules that appear active in many biochemical assays not
        because they bind the target but because they interfere with the assay
        itself (e.g. via aggregation, fluorescence, redox cycling).

        RDKit ships the PAINS-A/B/C filter catalog from Baell & Holloway (2010).
        A single match is enough to kill the molecule.

        Returns True if the molecule is PAINS-clean, False otherwise.
        """
        entry = self._pains_catalog.GetFirstMatch(mol)
        if entry is not None:
            # GetDescription() returns the PAINS pattern name, useful for debugging.
            result.kill_reason = f"PAINS hit: {entry.GetDescription()}"
            return False
        return True

    # ─────────────────────────────────────────────────────────────────
    # Check 5 — Drug-Likeness (Lipinski + Veber)
    # ─────────────────────────────────────────────────────────────────

    def _check_drug_likeness(self, mol, result: CheckResult) -> bool:
        """
        Enforce drug-likeness property ranges (Lipinski Ro5 + Veber rules).

        In Joe's data the main failure is MW > 550, almost always caused by
        molecules with 3+ sulfonamide groups (each adds ~79 Da).  Check 7
        catches the root cause; this check catches any remaining MW violators.

        Properties computed and stored on result.properties for reporting:
            MW, LogP, HBD, HBA, RotBonds, TPSA, Fsp3

        Returns True if all properties are within range, False at the first
        violation (and records which property failed).
        """
        props = {
            "MW":       Descriptors.MolWt(mol),
            "LogP":     Descriptors.MolLogP(mol),
            "HBD":      rdMolDescriptors.CalcNumHBD(mol),
            "HBA":      rdMolDescriptors.CalcNumHBA(mol),
            "RotBonds": rdMolDescriptors.CalcNumRotatableBonds(mol),
            "TPSA":     rdMolDescriptors.CalcTPSA(mol),
            "Fsp3":     rdMolDescriptors.CalcFractionCSP3(mol),
        }
        result.properties.update(props)

        for prop_name, (lo, hi) in DRUG_LIKENESS_RULES.items():
            value = props[prop_name]
            if lo is not None and value < lo:
                result.kill_reason = (
                    f"Drug-likeness: {prop_name} = {value:.2f} < {lo}"
                )
                return False
            if hi is not None and value > hi:
                result.kill_reason = (
                    f"Drug-likeness: {prop_name} = {value:.2f} > {hi}"
                )
                return False

        return True

    # ─────────────────────────────────────────────────────────────────
    # Check 6 — Synthetic Accessibility Score
    # ─────────────────────────────────────────────────────────────────

    def _check_sa_score(self, mol, result: CheckResult) -> bool:
        """
        Reject molecules that are synthetically inaccessible.

        The SA Score (Ertl & Schuffenhauer, 2009) estimates how hard a molecule
        is to synthesize using a fragment-frequency heuristic trained on known
        compounds.  Scale: 1 (trivially easy) → 10 (essentially impossible).

        This is the most expensive check (~1 ms) so it runs after the cheap
        structural and property filters.

        Returns True if SA score <= self.sa_score_limit (default 6.0).
        """
        sa = sascorer.calculateScore(mol)
        result.properties["sa_score"] = round(sa, 2)

        if sa > self.sa_score_limit:
            result.kill_reason = (
                f"SA score too high ({sa:.2f} > {self.sa_score_limit})"
            )
            return False
        return True

    # ─────────────────────────────────────────────────────────────────
    # Check 7 — Sulfonamide Count  ← kills 82% of Joe's data
    # ─────────────────────────────────────────────────────────────────

    def _check_sulfonamides(self, mol, result: CheckResult) -> bool:
        """
        Reject molecules with >= sulfonamide_limit sulfonamide groups.

        This single check is the most impactful filter in the pipeline.
        Joe's RL reward function has a bug that gives a docking bonus for
        sulfonamide groups near GID4's binding site.  SmileyLlama exploits
        this by stacking 3-5 sulfonamides per molecule, producing high
        docking scores without actually being good drug candidates.

        SMARTS: [#7]S(=O)(=O)  — nitrogen attached to a sulfonyl group.

        Kill threshold: >= 3 (configurable via sulfonamide_limit in __init__).
        Breakdown in Joe's 200-molecule dataset:
            1 sulfonamide  →  4 molecules  (PASS)
            2 sulfonamides → 32 molecules  (PASS)
            3 sulfonamides → 102 molecules (KILL)
            4 sulfonamides →  54 molecules (KILL)
            5 sulfonamides →   8 molecules (KILL)

        Returns True if count < sulfonamide_limit, False otherwise.
        """
        matches = mol.GetSubstructMatches(self._sulfonamide_pat)
        count   = len(matches)
        result.properties["sulfonamide_count"] = count

        if count >= self.sulfonamide_limit:
            result.kill_reason = (
                f"Sulfonamide overload ({count} >= {self.sulfonamide_limit})"
            )
            return False
        return True

    # ─────────────────────────────────────────────────────────────────
    # Check 8 — Salt Bridge Advisory  (DOES NOT KILL)
    # ─────────────────────────────────────────────────────────────────

    def _check_salt_bridge(self, mol, result: CheckResult):
        """
        Advisory check: flag whether the molecule has a basic amine capable
        of forming a salt bridge with GLU237 in GID4.

        GLU237 is the key residue in the binding hypothesis — molecules that
        interact with it tend to score better.  98% of Joe's dataset already
        has a salt-bridge group, meaning SmileyLlama has learned to include
        basic amines.  The problem is the sulfonamide overload that accompanies
        them, not the absence of amines.

        This check is ADVISORY: it never kills.  Findings are appended to
        result.warnings so they show up in reports but don't block molecules.
        """
        found_groups = []
        for name, pattern in self._salt_bridge:
            if mol.HasSubstructMatch(pattern):
                found_groups.append(name)

        if found_groups:
            result.warnings.append(
                f"Salt bridge group present: {', '.join(found_groups)}"
            )
        else:
            result.warnings.append("No salt bridge group detected (advisory)")

    # ─────────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────────

    @staticmethod
    def _parse_sdf(content: str) -> tuple:
        """
        Extract the SMILES and metadata fields from a raw SDF file string.

        The SDF files from top_poses.tar contain one molecule each with
        RDKit-style property blocks like:
            >  <smiles>
            COc1ccc(...)cc1

        Returns (smiles_string, metadata_dict).  Both are None on parse failure.
        """
        smiles   = None
        metadata = {}
        lines    = content.splitlines()

        i = 0
        while i < len(lines):
            line = lines[i].strip()

            # Property block header looks like:  >  <property_name>
            if line.startswith(">") and "<" in line:
                prop_name = line.split("<")[1].split(">")[0].strip()
                # Value is on the next non-empty line.
                i += 1
                while i < len(lines) and not lines[i].strip():
                    i += 1
                if i < len(lines):
                    value = lines[i].strip()
                    if prop_name == "smiles":
                        smiles = value
                    else:
                        metadata[prop_name] = value
            i += 1

        return smiles, metadata if smiles else (None, None)


# ─────────────────────────────────────────────────────────────────────────────
# CLI entry point — run directly to validate Joe's dataset
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="SynAgent MoleculeChecker")
    parser.add_argument(
        "--tar",
        default=r"top_poses.tar-3\top_poses.tar-3",
        help="Path to the top_poses tar file",
    )
    parser.add_argument(
        "--sulfonamide-limit", type=int, default=3,
        help="Kill molecules with >= N sulfonamide groups (default: 3)",
    )
    parser.add_argument(
        "--sa-limit", type=float, default=6.0,
        help="Kill molecules with SA score > N (default: 6.0)",
    )
    parser.add_argument(
        "--show-passed", action="store_true",
        help="Print SMILES and properties for molecules that pass all checks",
    )
    args = parser.parse_args()

    checker = MoleculeChecker(
        sulfonamide_limit=args.sulfonamide_limit,
        sa_score_limit=args.sa_limit,
    )

    print(f"Loading molecules from: {args.tar}")
    results = checker.check_from_tar(args.tar)

    checker.print_summary(results)

    if args.show_passed:
        print("Molecules that passed all checks:")
        print("-" * 55)
        for r in results:
            if r.passed:
                props = r.properties
                print(f"  SMILES      : {r.smiles}")
                print(f"  MW          : {props.get('MW', '?'):.1f}")
                print(f"  LogP        : {props.get('LogP', '?'):.2f}")
                print(f"  Charge      : {props.get('formal_charge', '?')}")
                print(f"  Sulfonamides: {props.get('sulfonamide_count', '?')}")
                print(f"  SA Score    : {props.get('sa_score', '?')}")
                print(f"  Warnings    : {'; '.join(r.warnings) or 'none'}")
                if r.protein:
                    print(f"  Protein     : {r.protein}  "
                          f"GID4 dock = {r.gid4_dock}  "
                          f"iMiner = {r.iminer}")
                print()
